apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-03-21T05:30:23Z
  generation: 1
  labels:
    run: presto-coordinator
  name: presto-coordinator
  namespace: prestodb
  resourceVersion: "2699021"
  selfLink: /apis/extensions/v1beta1/namespaces/prestodb/deployments/presto-coordinator
  uid: 7b57ebb5-0df7-11e7-b031-06ec1f6e0b23
spec:
  replicas: 1
  selector:
    matchLabels:
      run: presto-coordinator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: presto-coordinator
    spec:
      containers:
      - image: presto-coordinator
        imagePullPolicy: Always
        name: presto-coordinator
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2017-03-21T05:30:23Z
    lastUpdateTime: 2017-03-21T05:30:23Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
