apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: presto-coordinator
  name: presto-coordinator
  namespace: prestodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: presto-coordinator
    spec:
      containers:
      - image: asia.gcr.io/sandbox-159310/presto-coordinator:latest
        imagePullPolicy: Always
        name: presto-coordinator
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: presto-coordinator
